<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Datastructuren\Datastructuren.csproj" />
    <ProjectReference Include="..\ExceptionHandling\ExceptionHandling.csproj" />
    <ProjectReference Include="..\KlassenEnObjecten\KlassenEnObjecten.csproj" />
    <ProjectReference Include="..\Library\Library.csproj" />
    <ProjectReference Include="..\Objecten\Objecten.csproj" />
    <ProjectReference Include="..\Overerving\Overerving.csproj" />
  </ItemGroup>

</Project>
